$(document).ready(function() {
 
 $("#myndir").css("border-bottom", "thick solid #bdbdbd");

 var haed1 = ($("#myndatexti").height()) + 60;
 
 window.setInterval(function() {
 haed1 = ($("#myndatexti").height()) + 60;
 $("#litlarmyndirrammi").css("padding-bottom", haed1);
 }, 10);
 
 //Hlutir til ad fela
 $("#vidhengi").hide();
 $("#tenglaor2").hide();
 
 //Tenglar
 var orteljari = 0;
 $("#tenglar").click(function() {
 $("#vidhengi").slideToggle(300);
 if((orteljari%2)==0) {
 $("#tenglaor").hide();
 $("#tenglaor2").show();
 orteljari++;
 }
 else if((orteljari%2)!=0) {
 $("#tenglaor2").hide();
 $("#tenglaor").show();
 orteljari++;
 }
 });
 
 //Hovereffectar
 $(".linkar1").mouseenter(function() {
    $(this).css("color", "white");
  });
  
  $(".linkar1").mouseleave(function() {
    $(this).css("color", "#bdbdbd");
  });
  
  $(".vh2").mouseenter(function() {
    $(this).css("background-color", "#9de8bb");
  });
  
  $(".vh2").mouseleave(function() {
    $(this).css("background-color", "white");
  });
  
  $("#or1").mouseenter(function() {
	$(this).css("opacity", "0.0");
  });
  
  $("#or1").mouseleave(function() {
    $(this).css("opacity", "1.0");
  });
  
  $("#or2").mouseenter(function() {
    $(this).css("opacity", "0.0");
  });
  
  $("#or2").mouseleave(function() {
    $(this).css("opacity", "1.0");
  });

  //Til að skipta um mynd
  var myndasyning = new Array();
  myndasyning[0] = new Image();
  myndasyning[0].src = "img/myndir/1.jpg";
  myndasyning[1] = new Image();
  myndasyning[1].src = "img/myndir/2.jpg";
  myndasyning[2] = new Image();
  myndasyning[2].src = "img/myndir/3.jpg";
  myndasyning[3] = new Image();
  myndasyning[3].src = "img/myndir/4.jpg";
  myndasyning[4] = new Image();
  myndasyning[4].src = "img/myndir/5.jpg";
  myndasyning[5] = new Image();
  myndasyning[5].src = "img/myndir/6.jpg";
  myndasyning[6] = new Image();
  myndasyning[6].src = "img/myndir/7.jpg";
  myndasyning[7] = new Image();
  myndasyning[7].src = "img/myndir/8.jpg";
  myndasyning[8] = new Image();
  myndasyning[8].src = "img/myndir/9.jpg";
  myndasyning[9] = new Image();
  myndasyning[9].src = "img/myndir/10.jpg";
  myndasyning[10] = new Image();
  myndasyning[10].src = "img/myndir/11.jpg";
  myndasyning[11] = new Image();
  myndasyning[11].src = "img/myndir/12.jpg";
  myndasyning[12] = new Image();
  myndasyning[12].src = "img/myndir/13.jpg";
  myndasyning[13] = new Image();
  myndasyning[13].src = "img/myndir/14.jpg";
  myndasyning[14] = new Image();
  myndasyning[14].src = "img/myndir/15.jpg";
  myndasyning[15] = new Image();
  myndasyning[15].src = "img/myndir/16.jpg";
  myndasyning[16] = new Image();
  myndasyning[16].src = "img/myndir/17.jpg";
  myndasyning[17] = new Image();
  myndasyning[17].src = "img/myndir/18.jpg";
  myndasyning[18] = new Image();
  myndasyning[18].src = "img/myndir/19.jpg";
  myndasyning[19] = new Image();
  myndasyning[19].src = "img/myndir/20.jpg";
  myndasyning[20] = new Image();
  myndasyning[20].src = "img/myndir/21.jpg";
  myndasyning[21] = new Image();
  myndasyning[21].src = "img/myndir/22.jpg";
  myndasyning[22] = new Image();
  myndasyning[22].src = "img/myndir/23.jpg";
  myndasyning[23] = new Image();
  myndasyning[23].src = "img/myndir/24.jpg";
  myndasyning[24] = new Image();
  myndasyning[24].src = "img/myndir/25.jpg";
  myndasyning[25] = new Image();
  myndasyning[25].src = "img/myndir/26.jpg";
  myndasyning[26] = new Image();
  myndasyning[26].src = "img/myndir/27.JPG";
  myndasyning[27] = new Image();
  myndasyning[27].src = "img/myndir/28.JPG";
  myndasyning[28] = new Image();
  myndasyning[28].src = "img/myndir/29.JPG";
  myndasyning[29] = new Image();
  myndasyning[29].src = "img/myndir/30.JPG";
  myndasyning[30] = new Image();
  myndasyning[30].src = "img/myndir/31.JPG";
  myndasyning[31] = new Image();
  myndasyning[31].src = "img/myndir/32.JPG";
  myndasyning[32] = new Image();
  myndasyning[32].src = "img/myndir/33.JPG";
  myndasyning[33] = new Image();
  myndasyning[33].src = "img/myndir/34.JPG";
  myndasyning[34] = new Image();
  myndasyning[34].src = "img/myndir/35.JPG";
  myndasyning[35] = new Image();
  myndasyning[35].src = "img/myndir/36.JPG";
  myndasyning[36] = new Image();
  myndasyning[36].src = "img/myndir/37.jpg";
  myndasyning[37] = new Image();
  myndasyning[37].src = "img/myndir/38.JPG";
  myndasyning[38] = new Image();
  myndasyning[38].src = "img/myndir/39.jpg";
  myndasyning[39] = new Image();
  myndasyning[39].src = "img/myndir/40.jpg";
  myndasyning[40] = new Image();
  myndasyning[40].src = "img/myndir/41.jpg";
  myndasyning[41] = new Image();
  myndasyning[41].src = "img/myndir/42.jpg";
  myndasyning[42] = new Image();
  myndasyning[42].src = "img/myndir/43.jpg";
  myndasyning[43] = new Image();
  myndasyning[43].src = "img/myndir/44.jpg";
  myndasyning[44] = new Image();
  myndasyning[44].src = "img/myndir/45.jpg";
  myndasyning[45] = new Image();
  myndasyning[45].src = "img/myndir/46.jpg";
  myndasyning[46] = new Image();
  myndasyning[46].src = "img/myndir/47.jpg";
  myndasyning[47] = new Image();
  myndasyning[47].src = "img/myndir/48.jpg";
  myndasyning[48] = new Image();
  myndasyning[48].src = "img/myndir/49.jpg";
  myndasyning[49] = new Image();
  myndasyning[49].src = "img/myndir/50.jpg";
  myndasyning[50] = new Image();
  myndasyning[50].src = "img/myndir/51.jpg";
  myndasyning[51] = new Image();
  myndasyning[51].src = "img/myndir/52.jpg";
  myndasyning[52] = new Image();
  myndasyning[52].src = "img/myndir/53.jpg";
  myndasyning[53] = new Image();
  myndasyning[53].src = "img/myndir/54.jpg";
  myndasyning[54] = new Image();
  myndasyning[54].src = "img/myndir/55.jpg";
  myndasyning[55] = new Image();
  myndasyning[55].src = "img/myndir/56.jpg";
  myndasyning[56] = new Image();
  myndasyning[56].src = "img/myndir/57.jpg";
  myndasyning[57] = new Image();
  myndasyning[57].src = "img/myndir/58.jpg";
  myndasyning[58] = new Image();
  myndasyning[58].src = "img/myndir/59.jpg";
  myndasyning[59] = new Image();
  myndasyning[59].src = "img/myndir/60.jpg";
  myndasyning[60] = new Image();
  myndasyning[60].src = "img/myndir/61.jpg";
  myndasyning[61] = new Image();
  myndasyning[61].src = "img/myndir/62.jpg";
  myndasyning[62] = new Image();
  myndasyning[62].src = "img/myndir/63.jpg";
  myndasyning[63] = new Image();
  myndasyning[63].src = "img/myndir/64.jpg";
  myndasyning[64] = new Image();
  myndasyning[64].src = "img/myndir/65.jpg";
  myndasyning[65] = new Image();
  myndasyning[65].src = "img/myndir/66.jpg";
  myndasyning[66] = new Image();
  myndasyning[66].src = "img/myndir/67.jpg";
  myndasyning[67] = new Image();
  myndasyning[67].src = "img/myndir/68.jpg";
  myndasyning[68] = new Image();
  myndasyning[68].src = "img/myndir/69.jpg";
  myndasyning[69] = new Image();
  myndasyning[69].src = "img/myndir/70.jpg";
  myndasyning[70] = new Image();
  myndasyning[70].src = "img/myndir/71.jpg";
  myndasyning[71] = new Image();
  myndasyning[71].src = "img/myndir/72.jpg";
  myndasyning[72] = new Image();
  myndasyning[72].src = "img/myndir/73.jpg";
  myndasyning[73] = new Image();
  myndasyning[73].src = "img/myndir/74.jpg";
  myndasyning[74] = new Image();
  myndasyning[74].src = "img/myndir/75.jpg";
  myndasyning[75] = new Image();
  myndasyning[75].src = "img/myndir/76.jpg";
  myndasyning[76] = new Image();
  myndasyning[76].src = "img/myndir/77.jpg";
  myndasyning[77] = new Image();
  myndasyning[77].src = "img/myndir/78.jpg";
  myndasyning[78] = new Image();
  myndasyning[78].src = "img/myndir/79.jpg";
  myndasyning[79] = new Image();
  myndasyning[79].src = "img/myndir/80.jpg";
  myndasyning[80] = new Image();
  myndasyning[80].src = "img/myndir/81.jpg";
  myndasyning[81] = new Image();
  myndasyning[81].src = "img/myndir/82.jpg";
  myndasyning[82] = new Image();
  myndasyning[82].src = "img/myndir/83.jpg";
  myndasyning[83] = new Image();
  myndasyning[83].src = "img/myndir/84.jpg";
  myndasyning[84] = new Image();
  myndasyning[84].src = "img/myndir/85.jpg";
  myndasyning[85] = new Image();
  myndasyning[85].src = "img/myndir/86.jpg";
  myndasyning[86] = new Image();
  myndasyning[86].src = "img/myndir/87.jpg";
  myndasyning[87] = new Image();
  myndasyning[87].src = "img/myndir/88.jpg";
  myndasyning[88] = new Image();
  myndasyning[88].src = "img/myndir/89.jpg";
  myndasyning[89] = new Image();
  myndasyning[89].src = "img/myndir/90.jpg";
  myndasyning[90] = new Image();
  myndasyning[90].src = "img/myndir/91.jpg";
  myndasyning[91] = new Image();
  myndasyning[91].src = "img/myndir/92.jpg";
  myndasyning[92] = new Image();
  myndasyning[92].src = "img/myndir/93.jpg";
  myndasyning[93] = new Image();
  myndasyning[93].src = "img/myndir/94.jpg";
  myndasyning[94] = new Image();
  myndasyning[94].src = "img/myndir/95.jpg";
  myndasyning[95] = new Image();
  myndasyning[95].src = "img/myndir/96.jpg";
  myndasyning[96] = new Image();
  myndasyning[96].src = "img/myndir/97.jpg";
  myndasyning[97] = new Image();
  myndasyning[97].src = "img/myndir/98.jpg";
  myndasyning[98] = new Image();
  myndasyning[98].src = "img/myndir/99.jpg";
  myndasyning[99] = new Image();
  myndasyning[99].src = "img/myndir/100.jpg";
  myndasyning[100] = new Image();
  myndasyning[100].src = "img/myndir/101.jpg";
  myndasyning[101] = new Image();
  myndasyning[101].src = "img/myndir/102.jpg";
  myndasyning[102] = new Image();
  myndasyning[102].src = "img/myndir/103.jpg";
  myndasyning[103] = new Image();
  myndasyning[103].src = "img/myndir/104.jpg";
  myndasyning[104] = new Image();
  myndasyning[104].src = "img/myndir/105.jpg";
  myndasyning[105] = new Image();
  myndasyning[105].src = "img/myndir/106.jpg";
  myndasyning[106] = new Image();
  myndasyning[106].src = "img/myndir/107.jpg";
  myndasyning[107] = new Image();
  myndasyning[107].src = "img/myndir/108.jpg";
  myndasyning[108] = new Image();
  myndasyning[108].src = "img/myndir/109.jpg";
  myndasyning[109] = new Image();
  myndasyning[109].src = "img/myndir/110.jpg";
  myndasyning[110] = new Image();
  myndasyning[110].src = "img/myndir/111.jpg";
  myndasyning[111] = new Image();
  myndasyning[111].src = "img/myndir/112.jpg";
  myndasyning[112] = new Image();
  myndasyning[112].src = "img/myndir/113.jpg";
  myndasyning[113] = new Image();
  myndasyning[113].src = "img/myndir/114.jpg";
  myndasyning[114] = new Image();
  myndasyning[114].src = "img/myndir/115.jpg";
  myndasyning[115] = new Image();
  myndasyning[115].src = "img/myndir/116.jpg";
  myndasyning[116] = new Image();
  myndasyning[116].src = "img/myndir/117.jpg";
  myndasyning[117] = new Image();
  myndasyning[117].src = "img/myndir/118.jpg";
  myndasyning[118] = new Image();
  myndasyning[118].src = "img/myndir/119.jpg";
  myndasyning[119] = new Image();
  myndasyning[119].src = "img/myndir/120.jpg";
  myndasyning[120] = new Image();
  myndasyning[120].src = "img/myndir/121.jpg";
  myndasyning[121] = new Image();
  myndasyning[121].src = "img/myndir/122.jpg";
  myndasyning[122] = new Image();
  myndasyning[122].src = "img/myndir/123.jpg";
  myndasyning[123] = new Image();
  myndasyning[123].src = "img/myndir/124.jpg";
  myndasyning[124] = new Image();
  myndasyning[124].src = "img/myndir/125.jpg";
  myndasyning[125] = new Image();
  myndasyning[125].src = "img/myndir/126.jpg";
  myndasyning[126] = new Image();
  myndasyning[126].src = "img/myndir/127.jpg";
  myndasyning[127] = new Image();
  myndasyning[127].src = "img/myndir/128.jpg";
  myndasyning[128] = new Image();
  myndasyning[128].src = "img/myndir/129.jpg";
  myndasyning[129] = new Image();
  myndasyning[129].src = "img/myndir/130.jpg";
  myndasyning[130] = new Image();
  myndasyning[130].src = "img/myndir/131.jpg";
  myndasyning[131] = new Image();
  myndasyning[131].src = "img/myndir/132.jpg";
  
  var myndasyningtexti = new Array();
  myndasyningtexti[0] = "F.v. Soffía Vigfúsdóttir, Anna María Vigfúsdóttir og Þorgerður dóttir Rósu sem var systir Vigfúsar. Rósa bjó lengi á Seyðisfirði.";
  myndasyningtexti[1] = "Ólafur Gunnarsson";
  myndasyningtexti[2] = "Anna María Vigfúsdóttir";
  myndasyningtexti[3] = "Dóra Ólafsdóttir";
  myndasyningtexti[4] = "Baldvin Ólafsson, Gunnar Ólafsson, Árni Ólafsson og Baldvin Ringsted. Aftari röð: Sigurður Ringsted og Vigfús Ólafsson.";
  myndasyningtexti[5] = "Haraldur Ringsted.";
  myndasyningtexti[6] = "Hér eru Haraldur Halldórsson, Gunnar Ólafsson (með hvolpinn) og Baldvin Ólafsson en þá kemur Haraldur Ringsted. Aftastur er Sigurður Ringsted.";
  myndasyningtexti[7] = "Baldvin Ringsted, Kátur og Haraldur Halldórsson.";
  myndasyningtexti[8] = "Árni Ólafsson (t.v.) og Baldvin Ringsted.";
  myndasyningtexti[9] = "F.v. Guðríður, Dóra, Sigurjóna Hallgrímsdóttir og Marsibil (Billa).";
  myndasyningtexti[10] = "Haraldur Ringsted og ungur drengur. Veist þú hver hann er?";
  myndasyningtexti[11] = "Elín Ólafsdóttir og Dóra Ólafsdóttir.";
  myndasyningtexti[12] = "Þuríður Finnsdóttir (Finns Jónssonar), Dóra Ólafsdóttir, Ingibjörg Jónsdóttir. Þuríður og Ingibjörg komu frá Ísafirði.";
  myndasyningtexti[13] = "Hópmynd";
  myndasyningtexti[14] = "Hér má þekkja Elínu Ringsted, Baldvin bróður hennar og Jakobínu Gunnarsdóttur.";
  myndasyningtexti[15] = "Hér má þekkja (f.v.) Ólaf Gunnarsson, Önnu Maríu Vigfúsdóttur, Guðríði Ólafsdóttur, Elínu Ringsted, Guðríði Gunnarsdóttur. Líklega er það Ása sem stendur fremst. Þá má þekkja Baldvin Ringsted fyrir aftan Önnu Maríu (vinstra megin) en hægra megin stendur Árni Ólafsson. Líklega stendur Gunnar Ólafsson fyrir aftan Guðríði systur sína.";
  myndasyningtexti[16] = "Hópmynd";
  myndasyningtexti[17] = "Hópmynd";
  myndasyningtexti[18] = "Líklega er það Jakobína Anna Gunnarsdóttir sem er t.h. Hina þekkjum við ekki. Veistu þú meira?";
  myndasyningtexti[19] = "Erfitt er að þekkja þetta fólk - en líklega er Vigfús Ólafsson lengst til hægri.";
  myndasyningtexti[20] = "Par";
  myndasyningtexti[21] = "Hér má þekkja Önnu Pálinu Halldórsdóttur, Vigfús, Harald Ringsted, Sigurð Ringsted. Í aftari röð eru Gunnar Ólafsson, Haraldur Halldórsson, Guðríður Ólafsdóttir og bróðir hennar Baldvin. Ungur með með derhúfu og hönd á hné er Baldvin Ringsted.";
  myndasyningtexti[22] = "Búbba og Mummi";
  myndasyningtexti[23] = "Hér má sjá Gunnar Ólafsson og hundinn Kát. Í baksýn er túnið í Sigtúnum. Tv. eru kartöflugarðar. Húsið t.v. var í eigu Steingríms og Önnu - og að sögn DÓ hét það land.";
  myndasyningtexti[24] = "Anna María og Ólafur í Svarðagröfunum";
  myndasyningtexti[25] = "Gunnur Ólafsdóttir";
  myndasyningtexti[26] = "Höfði";
  myndasyningtexti[27] = "Þóra Soffía og Lauga í Vallholti vinkona hennar";
  myndasyningtexti[28] = "Elín Ringsted, Ella.";
  myndasyningtexti[29] = "Mæðgur. Dóra og Ása";
  myndasyningtexti[30] = "Ása og Þóra Soffía";
  myndasyningtexti[31] = "Ása";
  myndasyningtexti[32] = "Ása og Þóra Soffía";
  myndasyningtexti[33] = "Búbba, Ella, Ása og Þóra Soffía";
  myndasyningtexti[34] = "Björn í Höfða";
  myndasyningtexti[35] = "Óþekkt";
  myndasyningtexti[36] = "Sigtún";
  myndasyningtexti[37] = "Sigtún";
  myndasyningtexti[38] = "Sigtún";
  myndasyningtexti[39] = "Þóra Soffía ung";
  myndasyningtexti[40] = "Gunnar Ólafs, Siggi Ring, Haraldur Halldórsson.";
  myndasyningtexti[41] = "Ása, Dóra og Búbba";
  myndasyningtexti[42] = "Marta Baldvinsdóttir á Kljáströnd";
  myndasyningtexti[43] = "Þóra Rósa Vigfúsdóttir ung.";
  myndasyningtexti[44] = "Dóra og Gunnur Ólafsdætur";
  myndasyningtexti[45] = "Stuðningsmenn Magna";
  myndasyningtexti[46] = "Árni læknir og Hrefna kona hans";
  myndasyningtexti[47] = "Baldvin Gunnarsson, eldri";
  myndasyningtexti[48] = "Á sjó";
  myndasyningtexti[49] = "Á sjó";
  myndasyningtexti[50] = "Þórir og Búbba.";
  myndasyningtexti[51] = "Gunnar Ólafsson í meyjafans.";
  myndasyningtexti[52] = "Anna María með barn.";
  myndasyningtexti[53] = "Baldvin Ringsted, Haraldur Halldórsson og ókunnur maður.";
  myndasyningtexti[54] = "Krakkar á tröppunum á Kljáströnd";
  myndasyningtexti[55] = "Sveitaferð";
  myndasyningtexti[56] = "Búbba og Dóra";
  myndasyningtexti[57] = "Maja og Ágústa, Þessi er tekin á efri hæðinni í Reynivöllum 8, sjálfsagt í fermingarveislu.";
  myndasyningtexti[58] = "Mæðgur, Dóra og Ása.";
  myndasyningtexti[59] = "Fólk í skógarferð.";
  myndasyningtexti[60] = "Kljástrendingar norðan við Önnu Sveinshús. Þarna eru m.a. Ólafur Gunnarsson, Anna María, Vigfús, Dóra Ól. og Dóra hans Vigga o.fl.";
  myndasyningtexti[61] = "Gunnur og Dóra á tröppunum við Sigtún.";
  myndasyningtexti[62] = "Kona með barn.";
  myndasyningtexti[63] = "Þóra Soffía og bræðurnir Gunni og Mummi Haraldssynir";
  myndasyningtexti[64] = "Búbba, Ása, Mummi og Dóra";
  myndasyningtexti[65] = "Systurnar Búbba og Gunnur Ólafsdætur";
  myndasyningtexti[66] = "Dóra Ólafs og vinkona";
  myndasyningtexti[67] = "Stuðningsmenn MagnaFC";
  myndasyningtexti[68] = "Stuðningsmenn";
  myndasyningtexti[69] = "Fólk óþekkt";
  myndasyningtexti[70] = "Marta Baldvinsdóttir";
  myndasyningtexti[71] = "Baldvin bróðir Ólafs og Guðríðar sem dó ungur, lengst til vinstri";
  myndasyningtexti[72] = "Þóra Soffía og Ása";
  myndasyningtexti[73] = "Marta Baldvinsdóttir á Kljáströnd";
  myndasyningtexti[74] = "Þóra Rósa Vigfúsdóttir í hattabúðinni sinni";
  myndasyningtexti[75] = "Pétur";
  myndasyningtexti[76] = "Kljáströnd";
  myndasyningtexti[77] = "Ólafur Gunnarsson við Sigtún";
  myndasyningtexti[78] = "Búbba, Gunnur, Þóra og Ella";
  myndasyningtexti[79] = "Anna, Ása og Þóra";
  myndasyningtexti[80] = "Guðríður Gunnarsdóttir með Gunni Ringsted barnabarn sitt";
  myndasyningtexti[81] = "Hundurinn Pétur og barn";
  myndasyningtexti[82] = "Anna María Vigfúsdóttir fermd";
  myndasyningtexti[83] = "Ella og Pétur";
  myndasyningtexti[84] = "Anna María og Þóra Soffía";
  myndasyningtexti[85] = "Þóra og Ása";
  myndasyningtexti[86] = "Árni, Þóra og óþekkt kona í London";
  myndasyningtexti[87] = "Höefnershúsið má muna sinn fífil fegri.";
  myndasyningtexti[88] = "Þóra Soffía í hópi skíðamanna";
  myndasyningtexti[89] = "Barn og belja -Mummi Búbbu";
  myndasyningtexti[90] = "Þóra Soffía og María í Höfða";
  myndasyningtexti[91] = "Vigfús Ólafsson";
  myndasyningtexti[92] = "Viggi á hestbaki.";
  myndasyningtexti[93] = "Þóra Soffía og vinkona.";
  myndasyningtexti[94] = "Ella í skóginum.";
  myndasyningtexti[95] = "Ása og Þóra Soffía.";
  myndasyningtexti[96] = "Guðríður Hjaltested síðari kona Gunnars Ólafssonar í Höfða, afi Ólafs og Guðríðar";
  myndasyningtexti[97] = "Baldvin Ringsted o.fl";
  myndasyningtexti[98] = "Börn og hundar, Ása";
  myndasyningtexti[99] = "Þarna er Óli Balda, Þóra Soffía úti í horni og líklega Höfðasystkyni";
  myndasyningtexti[100] = "Krakkar á Kljáströnd";
  myndasyningtexti[101] = "Þóra";
  myndasyningtexti[102] = "Dóra Ólafs og fleiri líklega af símanum";
  myndasyningtexti[103] = "Árni Ól. o.fl";
  myndasyningtexti[104] = "Árni Ólafsson";
  myndasyningtexti[105] = "Fleiri krakkar á Kljáströnd";
  myndasyningtexti[106] = "Þorbjörg dóttir Rósu Vigfúsdóttur á Seyðisfirði giftir sig.";
  myndasyningtexti[107] = "Nils maður Þóru frænku (Þóru Vigfúsdóttur)";
  myndasyningtexti[108] = "Anna María lengst til hægri með námsmeyjum í Danaveldi.";
  myndasyningtexti[109] = "Nils Christiansen maður Þóru Rósu Vigfúsdóttur.";
  myndasyningtexti[110] = "Þóra Rósa í Danmörku.";
  myndasyningtexti[111] = "Dóttir Árna læknis";
  myndasyningtexti[112] = "Sigurður Ringsted.";
  myndasyningtexti[113] = "Anna María Vigfúsdóttir til vinstri með skólasystrum á dönskum húsmæðraskóla.";
  myndasyningtexti[114] = "Þorbjörg dóttir Rósu Vigfúsdóttur.";
  myndasyningtexti[115] = "Rósa Vigfúsdóttir og Þorgerður dóttir hennar með börn.";
  myndasyningtexti[116] = "Óþekkt kona fylgdi myndum frá Kljáströnd.";
  myndasyningtexti[117] = "Gæti verið sonur Árna læknis.";
  myndasyningtexti[118] = "Guðríður Gunnarsdóttir.";
  myndasyningtexti[119] = "Þóra Soffía og Mummi á hjólinu hans Óla Balda við Sigtún";
  myndasyningtexti[120] = "Sigtún séð af sjó";
  myndasyningtexti[121] = "Anna María og Ólafur í Svarðagröfunum";
  myndasyningtexti[122] = "Kljáströnd málverk eftir Mattías.";
  myndasyningtexti[123] = "Kljáströnd-e. Árna Elfar";
  myndasyningtexti[124] = "Systkynin frá Hellu, Vigfús, Þóra, Vilhelm, Soffía og Anna María, Vigfúsbörn.";
  myndasyningtexti[125] = "Ólafur og Anna í stofunni á Kljáströnd.";
  myndasyningtexti[126] = "Búbba og dúkka";
  myndasyningtexti[127] = "Guðríður Ólafsdóttir (Búbba)";
  myndasyningtexti[128] = "Þórir, Sigurður Ringsted, Balvin Ringsted og Vigfús Vigfússon í fermingu Kela";
  myndasyningtexti[129] = "Búbba, Anna María, Þórir og Dóra";
  myndasyningtexti[130] = "Loftmynd";
  myndasyningtexti[131] = "Loftmynd";
  
  var litlarmyndir = new Array();
  litlarmyndir[0] = document.getElementById("litilmynd1");
  litlarmyndir[1] = document.getElementById("litilmynd2");
  litlarmyndir[2] = document.getElementById("litilmynd3");
  litlarmyndir[3] = document.getElementById("litilmynd4");
  litlarmyndir[4] = document.getElementById("litilmynd5");
  litlarmyndir[5] = document.getElementById("litilmynd6");
  litlarmyndir[6] = document.getElementById("litilmynd7");
  litlarmyndir[7] = document.getElementById("litilmynd8");
  litlarmyndir[8] = document.getElementById("litilmynd9");
  litlarmyndir[9] = document.getElementById("litilmynd10");
  litlarmyndir[10] = document.getElementById("litilmynd11");
  litlarmyndir[11] = document.getElementById("litilmynd12");
  litlarmyndir[12] = document.getElementById("litilmynd13");
  litlarmyndir[13] = document.getElementById("litilmynd14");
  litlarmyndir[14] = document.getElementById("litilmynd15");
  litlarmyndir[15] = document.getElementById("litilmynd16");
  litlarmyndir[16] = document.getElementById("litilmynd17");
  litlarmyndir[17] = document.getElementById("litilmynd18");
  litlarmyndir[18] = document.getElementById("litilmynd19");
  litlarmyndir[19] = document.getElementById("litilmynd20");
  litlarmyndir[20] = document.getElementById("litilmynd21");
  litlarmyndir[21] = document.getElementById("litilmynd22");
  litlarmyndir[22] = document.getElementById("litilmynd23");
  litlarmyndir[23] = document.getElementById("litilmynd24");  
  litlarmyndir[24] = document.getElementById("litilmynd25"); 
  litlarmyndir[25] = document.getElementById("litilmynd26"); 
  litlarmyndir[26] = document.getElementById("litilmynd27"); 
  litlarmyndir[27] = document.getElementById("litilmynd28"); 
  litlarmyndir[28] = document.getElementById("litilmynd29"); 
  litlarmyndir[29] = document.getElementById("litilmynd30"); 
  litlarmyndir[30] = document.getElementById("litilmynd31"); 
  litlarmyndir[31] = document.getElementById("litilmynd32"); 
  litlarmyndir[32] = document.getElementById("litilmynd33"); 
  litlarmyndir[33] = document.getElementById("litilmynd34"); 
  litlarmyndir[34] = document.getElementById("litilmynd35"); 
  litlarmyndir[35] = document.getElementById("litilmynd36"); 
  litlarmyndir[36] = document.getElementById("litilmynd37"); 
  litlarmyndir[37] = document.getElementById("litilmynd38"); 
  litlarmyndir[38] = document.getElementById("litilmynd39"); 
  litlarmyndir[39] = document.getElementById("litilmynd40");
  litlarmyndir[40] = document.getElementById("litilmynd41");
  litlarmyndir[41] = document.getElementById("litilmynd42");
  litlarmyndir[42] = document.getElementById("litilmynd43");
  litlarmyndir[43] = document.getElementById("litilmynd44");  
  litlarmyndir[44] = document.getElementById("litilmynd45"); 
  litlarmyndir[45] = document.getElementById("litilmynd46"); 
  litlarmyndir[46] = document.getElementById("litilmynd47"); 
  litlarmyndir[47] = document.getElementById("litilmynd48"); 
  litlarmyndir[48] = document.getElementById("litilmynd49"); 
  litlarmyndir[49] = document.getElementById("litilmynd50"); 
  litlarmyndir[50] = document.getElementById("litilmynd51"); 
  litlarmyndir[51] = document.getElementById("litilmynd52"); 
  litlarmyndir[52] = document.getElementById("litilmynd53"); 
  litlarmyndir[53] = document.getElementById("litilmynd54"); 
  litlarmyndir[54] = document.getElementById("litilmynd55"); 
  litlarmyndir[55] = document.getElementById("litilmynd56"); 
  litlarmyndir[56] = document.getElementById("litilmynd57"); 
  litlarmyndir[57] = document.getElementById("litilmynd58"); 
  litlarmyndir[58] = document.getElementById("litilmynd59"); 
  litlarmyndir[59] = document.getElementById("litilmynd60");
  litlarmyndir[60] = document.getElementById("litilmynd61");
  litlarmyndir[61] = document.getElementById("litilmynd62");
  litlarmyndir[62] = document.getElementById("litilmynd63");
  litlarmyndir[63] = document.getElementById("litilmynd64");  
  litlarmyndir[64] = document.getElementById("litilmynd65"); 
  litlarmyndir[65] = document.getElementById("litilmynd66"); 
  litlarmyndir[66] = document.getElementById("litilmynd67"); 
  litlarmyndir[67] = document.getElementById("litilmynd68"); 
  litlarmyndir[68] = document.getElementById("litilmynd69"); 
  litlarmyndir[69] = document.getElementById("litilmynd70"); 
  litlarmyndir[70] = document.getElementById("litilmynd71"); 
  litlarmyndir[71] = document.getElementById("litilmynd72"); 
  litlarmyndir[72] = document.getElementById("litilmynd73"); 
  litlarmyndir[73] = document.getElementById("litilmynd74"); 
  litlarmyndir[74] = document.getElementById("litilmynd75"); 
  litlarmyndir[75] = document.getElementById("litilmynd76"); 
  litlarmyndir[76] = document.getElementById("litilmynd77"); 
  litlarmyndir[77] = document.getElementById("litilmynd78"); 
  litlarmyndir[78] = document.getElementById("litilmynd79"); 
  litlarmyndir[79] = document.getElementById("litilmynd80");
  litlarmyndir[80] = document.getElementById("litilmynd81");
  litlarmyndir[81] = document.getElementById("litilmynd82");
  litlarmyndir[82] = document.getElementById("litilmynd83");
  litlarmyndir[83] = document.getElementById("litilmynd84");  
  litlarmyndir[84] = document.getElementById("litilmynd85"); 
  litlarmyndir[85] = document.getElementById("litilmynd86"); 
  litlarmyndir[86] = document.getElementById("litilmynd87"); 
  litlarmyndir[87] = document.getElementById("litilmynd88"); 
  litlarmyndir[88] = document.getElementById("litilmynd89"); 
  litlarmyndir[89] = document.getElementById("litilmynd90"); 
  litlarmyndir[90] = document.getElementById("litilmynd91"); 
  litlarmyndir[91] = document.getElementById("litilmynd92"); 
  litlarmyndir[92] = document.getElementById("litilmynd93"); 
  litlarmyndir[93] = document.getElementById("litilmynd94"); 
  litlarmyndir[94] = document.getElementById("litilmynd95"); 
  litlarmyndir[95] = document.getElementById("litilmynd96"); 
  litlarmyndir[96] = document.getElementById("litilmynd97"); 
  litlarmyndir[97] = document.getElementById("litilmynd98"); 
  litlarmyndir[98] = document.getElementById("litilmynd99"); 
  litlarmyndir[99] = document.getElementById("litilmynd100");   
  litlarmyndir[100] = document.getElementById("litilmynd101");
  litlarmyndir[101] = document.getElementById("litilmynd102");
  litlarmyndir[102] = document.getElementById("litilmynd103");
  litlarmyndir[103] = document.getElementById("litilmynd104");  
  litlarmyndir[104] = document.getElementById("litilmynd105"); 
  litlarmyndir[105] = document.getElementById("litilmynd106"); 
  litlarmyndir[106] = document.getElementById("litilmynd107"); 
  litlarmyndir[107] = document.getElementById("litilmynd108"); 
  litlarmyndir[108] = document.getElementById("litilmynd109"); 
  litlarmyndir[109] = document.getElementById("litilmynd110"); 
  litlarmyndir[110] = document.getElementById("litilmynd111"); 
  litlarmyndir[111] = document.getElementById("litilmynd112"); 
  litlarmyndir[112] = document.getElementById("litilmynd113"); 
  litlarmyndir[113] = document.getElementById("litilmynd114"); 
  litlarmyndir[114] = document.getElementById("litilmynd115"); 
  litlarmyndir[115] = document.getElementById("litilmynd116"); 
  litlarmyndir[116] = document.getElementById("litilmynd117"); 
  litlarmyndir[117] = document.getElementById("litilmynd118"); 
  litlarmyndir[118] = document.getElementById("litilmynd119"); 
  litlarmyndir[119] = document.getElementById("litilmynd120");
  litlarmyndir[120] = document.getElementById("litilmynd121");
  litlarmyndir[121] = document.getElementById("litilmynd122");
  litlarmyndir[122] = document.getElementById("litilmynd123");
  litlarmyndir[123] = document.getElementById("litilmynd124");
  litlarmyndir[124] = document.getElementById("litilmynd125");
  litlarmyndir[125] = document.getElementById("litilmynd126");
  litlarmyndir[126] = document.getElementById("litilmynd127");
  litlarmyndir[127] = document.getElementById("litilmynd128");
  litlarmyndir[128] = document.getElementById("litilmynd129");
  litlarmyndir[129] = document.getElementById("litilmynd130");
  litlarmyndir[130] = document.getElementById("litilmynd131");
  litlarmyndir[131] = document.getElementById("litilmynd132");
  
  var litlarm = new Array();
  litlarm[0] = document.getElementById("litilm1");
  litlarm[1] = document.getElementById("litilm2");
  litlarm[2] = document.getElementById("litilm3");
  litlarm[3] = document.getElementById("litilm4");
  litlarm[4] = document.getElementById("litilm5");
  litlarm[5] = document.getElementById("litilm6");
  litlarm[6] = document.getElementById("litilm7");
  litlarm[7] = document.getElementById("litilm8");
  litlarm[8] = document.getElementById("litilm9");
  litlarm[9] = document.getElementById("litilm10");
  litlarm[10] = document.getElementById("litilm11");
  litlarm[11] = document.getElementById("litilm12");
  litlarm[12] = document.getElementById("litilm13");
  litlarm[13] = document.getElementById("litilm14");
  litlarm[14] = document.getElementById("litilm15");
  litlarm[15] = document.getElementById("litilm16");
  litlarm[16] = document.getElementById("litilm17");
  litlarm[17] = document.getElementById("litilm18");
  litlarm[18] = document.getElementById("litilm19");
  litlarm[19] = document.getElementById("litilm20");
  litlarm[20] = document.getElementById("litilm21");
  litlarm[21] = document.getElementById("litilm22");
  litlarm[22] = document.getElementById("litilm23");
  litlarm[23] = document.getElementById("litilm24");
  litlarm[24] = document.getElementById("litilm25");
  litlarm[25] = document.getElementById("litilm26");
  litlarm[26] = document.getElementById("litilm27");
  litlarm[27] = document.getElementById("litilm28");
  litlarm[28] = document.getElementById("litilm29");
  litlarm[29] = document.getElementById("litilm30");
  litlarm[30] = document.getElementById("litilm31");
  litlarm[31] = document.getElementById("litilm32");
  litlarm[32] = document.getElementById("litilm33");
  litlarm[33] = document.getElementById("litilm34");
  litlarm[34] = document.getElementById("litilm35");
  litlarm[35] = document.getElementById("litilm36");
  litlarm[36] = document.getElementById("litilm37");
  litlarm[37] = document.getElementById("litilm38");
  litlarm[38] = document.getElementById("litilm39");
  litlarm[39] = document.getElementById("litilm40");
  litlarm[40] = document.getElementById("litilm41");
  litlarm[41] = document.getElementById("litilm42");
  litlarm[42] = document.getElementById("litilm43");
  litlarm[43] = document.getElementById("litilm44");
  litlarm[44] = document.getElementById("litilm45");
  litlarm[45] = document.getElementById("litilm46");
  litlarm[46] = document.getElementById("litilm47");
  litlarm[47] = document.getElementById("litilm48");
  litlarm[48] = document.getElementById("litilm49");
  litlarm[49] = document.getElementById("litilm50");
  litlarm[50] = document.getElementById("litilm51");
  litlarm[51] = document.getElementById("litilm52");
  litlarm[52] = document.getElementById("litilm53");
  litlarm[53] = document.getElementById("litilm54");
  litlarm[54] = document.getElementById("litilm55");
  litlarm[55] = document.getElementById("litilm56");
  litlarm[56] = document.getElementById("litilm57");
  litlarm[57] = document.getElementById("litilm58");
  litlarm[58] = document.getElementById("litilm59");
  litlarm[59] = document.getElementById("litilm60");
  litlarm[60] = document.getElementById("litilm61");
  litlarm[61] = document.getElementById("litilm62");
  litlarm[62] = document.getElementById("litilm63");
  litlarm[63] = document.getElementById("litilm64");
  litlarm[64] = document.getElementById("litilm65");
  litlarm[65] = document.getElementById("litilm66");
  litlarm[66] = document.getElementById("litilm67");
  litlarm[67] = document.getElementById("litilm68");
  litlarm[68] = document.getElementById("litilm69");
  litlarm[69] = document.getElementById("litilm70");
  litlarm[70] = document.getElementById("litilm71");
  litlarm[71] = document.getElementById("litilm72");
  litlarm[72] = document.getElementById("litilm73");
  litlarm[73] = document.getElementById("litilm74");
  litlarm[74] = document.getElementById("litilm75");
  litlarm[75] = document.getElementById("litilm76");
  litlarm[76] = document.getElementById("litilm77");
  litlarm[77] = document.getElementById("litilm78");
  litlarm[78] = document.getElementById("litilm79");
  litlarm[79] = document.getElementById("litilm80");
  litlarm[80] = document.getElementById("litilm81");
  litlarm[81] = document.getElementById("litilm82");
  litlarm[82] = document.getElementById("litilm83");
  litlarm[83] = document.getElementById("litilm84");
  litlarm[84] = document.getElementById("litilm85");
  litlarm[85] = document.getElementById("litilm86");
  litlarm[86] = document.getElementById("litilm87");
  litlarm[87] = document.getElementById("litilm88");
  litlarm[88] = document.getElementById("litilm89");
  litlarm[89] = document.getElementById("litilm90");
  litlarm[90] = document.getElementById("litilm91");
  litlarm[91] = document.getElementById("litilm92");
  litlarm[92] = document.getElementById("litilm93");
  litlarm[93] = document.getElementById("litilm94");
  litlarm[94] = document.getElementById("litilm95");
  litlarm[95] = document.getElementById("litilm96");
  litlarm[96] = document.getElementById("litilm97");
  litlarm[97] = document.getElementById("litilm98");
  litlarm[98] = document.getElementById("litilm99");
  litlarm[99] = document.getElementById("litilm100");
  litlarm[100] = document.getElementById("litilm101");
  litlarm[101] = document.getElementById("litilm102");
  litlarm[102] = document.getElementById("litilm103");
  litlarm[103] = document.getElementById("litilm104");
  litlarm[104] = document.getElementById("litilm105");
  litlarm[105] = document.getElementById("litilm106");
  litlarm[106] = document.getElementById("litilm107");
  litlarm[107] = document.getElementById("litilm108");
  litlarm[108] = document.getElementById("litilm109");
  litlarm[109] = document.getElementById("litilm110");
  litlarm[110] = document.getElementById("litilm111");
  litlarm[111] = document.getElementById("litilm112");
  litlarm[112] = document.getElementById("litilm113");
  litlarm[113] = document.getElementById("litilm114");
  litlarm[114] = document.getElementById("litilm115");
  litlarm[115] = document.getElementById("litilm116");
  litlarm[116] = document.getElementById("litilm117");
  litlarm[117] = document.getElementById("litilm118");
  litlarm[118] = document.getElementById("litilm119");
  litlarm[119] = document.getElementById("litilm120");
  litlarm[120] = document.getElementById("litilm121");
  litlarm[121] = document.getElementById("litilm122");
  litlarm[122] = document.getElementById("litilm123");
  litlarm[123] = document.getElementById("litilm124");
  litlarm[124] = document.getElementById("litilm125");
  litlarm[125] = document.getElementById("litilm126");
  litlarm[126] = document.getElementById("litilm127");
  litlarm[127] = document.getElementById("litilm128");
  litlarm[128] = document.getElementById("litilm129");
  litlarm[129] = document.getElementById("litilm130");
  litlarm[130] = document.getElementById("litilm131");
  litlarm[131] = document.getElementById("litilm132");
  
  var thumbnail = new Array();
  thumbnail[0] = new Image();
  thumbnail[0].src = "img/myndir/thumbnail/1.jpg";
  thumbnail[1] = new Image();
  thumbnail[1].src = "img/myndir/thumbnail/2.jpg";
  thumbnail[2] = new Image();
  thumbnail[2].src = "img/myndir/thumbnail/3.jpg";
  thumbnail[3] = new Image();
  thumbnail[3].src = "img/myndir/thumbnail/4.jpg";
  thumbnail[4] = new Image();
  thumbnail[4].src = "img/myndir/thumbnail/5.jpg";
  thumbnail[5] = new Image();
  thumbnail[5].src = "img/myndir/thumbnail/6.jpg";
  thumbnail[6] = new Image();
  thumbnail[6].src = "img/myndir/thumbnail/7.jpg";
  thumbnail[7] = new Image();
  thumbnail[7].src = "img/myndir/thumbnail/8.jpg";
  thumbnail[8] = new Image();
  thumbnail[8].src = "img/myndir/thumbnail/9.jpg";
  thumbnail[9] = new Image();
  thumbnail[9].src = "img/myndir/thumbnail/10.jpg";
  thumbnail[10] = new Image();
  thumbnail[10].src = "img/myndir/thumbnail/11.jpg";
  thumbnail[11] = new Image();
  thumbnail[11].src = "img/myndir/thumbnail/12.jpg";
  thumbnail[12] = new Image();
  thumbnail[12].src = "img/myndir/thumbnail/13.jpg";
  thumbnail[13] = new Image();
  thumbnail[13].src = "img/myndir/thumbnail/14.jpg";
  thumbnail[14] = new Image();
  thumbnail[14].src = "img/myndir/thumbnail/15.jpg";
  thumbnail[15] = new Image();
  thumbnail[15].src = "img/myndir/thumbnail/16.jpg";
  thumbnail[16] = new Image();
  thumbnail[16].src = "img/myndir/thumbnail/17.jpg";
  thumbnail[17] = new Image();
  thumbnail[17].src = "img/myndir/thumbnail/18.jpg";
  thumbnail[18] = new Image();
  thumbnail[18].src = "img/myndir/thumbnail/19.jpg";
  thumbnail[19] = new Image();
  thumbnail[19].src = "img/myndir/thumbnail/20.jpg";
  thumbnail[20] = new Image();
  thumbnail[20].src = "img/myndir/thumbnail/21.jpg";
  thumbnail[21] = new Image();
  thumbnail[21].src = "img/myndir/thumbnail/22.jpg";
  thumbnail[22] = new Image();
  thumbnail[22].src = "img/myndir/thumbnail/23.jpg";
  thumbnail[23] = new Image();
  thumbnail[23].src = "img/myndir/thumbnail/24.jpg";
  thumbnail[24] = new Image();
  thumbnail[24].src = "img/myndir/thumbnail/25.jpg";
  thumbnail[25] = new Image();
  thumbnail[25].src = "img/myndir/thumbnail/26.jpg";
  thumbnail[26] = new Image();
  thumbnail[26].src = "img/myndir/thumbnail/27.JPG";
  thumbnail[27] = new Image();
  thumbnail[27].src = "img/myndir/thumbnail/28.JPG";
  thumbnail[28] = new Image();
  thumbnail[28].src = "img/myndir/thumbnail/29.JPG";
  thumbnail[29] = new Image();
  thumbnail[29].src = "img/myndir/thumbnail/30.JPG";
  thumbnail[30] = new Image();
  thumbnail[30].src = "img/myndir/thumbnail/31.JPG";
  thumbnail[31] = new Image();
  thumbnail[31].src = "img/myndir/thumbnail/32.JPG";
  thumbnail[32] = new Image();
  thumbnail[32].src = "img/myndir/thumbnail/33.JPG";
  thumbnail[33] = new Image();
  thumbnail[33].src = "img/myndir/thumbnail/34.JPG";
  thumbnail[34] = new Image();
  thumbnail[34].src = "img/myndir/thumbnail/35.JPG";
  thumbnail[35] = new Image();
  thumbnail[35].src = "img/myndir/thumbnail/36.JPG";
  thumbnail[36] = new Image();
  thumbnail[36].src = "img/myndir/thumbnail/37.jpg";
  thumbnail[37] = new Image();
  thumbnail[37].src = "img/myndir/thumbnail/38.JPG";
  thumbnail[38] = new Image();
  thumbnail[38].src = "img/myndir/thumbnail/39.jpg";
  thumbnail[39] = new Image();
  thumbnail[39].src = "img/myndir/thumbnail/40.jpg";
  thumbnail[40] = new Image();
  thumbnail[40].src = "img/myndir/thumbnail/41.jpg";
  thumbnail[41] = new Image();
  thumbnail[41].src = "img/myndir/thumbnail/42.jpg";
  thumbnail[42] = new Image();
  thumbnail[42].src = "img/myndir/thumbnail/43.jpg";
  thumbnail[43] = new Image();
  thumbnail[43].src = "img/myndir/thumbnail/44.jpg";
  thumbnail[44] = new Image();
  thumbnail[44].src = "img/myndir/thumbnail/45.jpg";
  thumbnail[45] = new Image();
  thumbnail[45].src = "img/myndir/thumbnail/46.jpg";
  thumbnail[46] = new Image();
  thumbnail[46].src = "img/myndir/thumbnail/47.jpg";
  thumbnail[47] = new Image();
  thumbnail[47].src = "img/myndir/thumbnail/48.jpg";
  thumbnail[48] = new Image();
  thumbnail[48].src = "img/myndir/thumbnail/49.jpg";
  thumbnail[49] = new Image();
  thumbnail[49].src = "img/myndir/thumbnail/50.jpg";
  thumbnail[50] = new Image();
  thumbnail[50].src = "img/myndir/thumbnail/51.jpg";
  thumbnail[51] = new Image();
  thumbnail[51].src = "img/myndir/thumbnail/52.jpg";
  thumbnail[52] = new Image();
  thumbnail[52].src = "img/myndir/thumbnail/53.jpg";
  thumbnail[53] = new Image();
  thumbnail[53].src = "img/myndir/thumbnail/54.jpg";
  thumbnail[54] = new Image();
  thumbnail[54].src = "img/myndir/thumbnail/55.jpg";
  thumbnail[55] = new Image();
  thumbnail[55].src = "img/myndir/thumbnail/56.jpg";
  thumbnail[56] = new Image();
  thumbnail[56].src = "img/myndir/thumbnail/57.jpg";
  thumbnail[57] = new Image();
  thumbnail[57].src = "img/myndir/thumbnail/58.jpg";
  thumbnail[58] = new Image();
  thumbnail[58].src = "img/myndir/thumbnail/59.jpg";
  thumbnail[59] = new Image();
  thumbnail[59].src = "img/myndir/thumbnail/60.jpg";
  thumbnail[60] = new Image();
  thumbnail[60].src = "img/myndir/thumbnail/61.jpg";
  thumbnail[61] = new Image();
  thumbnail[61].src = "img/myndir/thumbnail/62.jpg";
  thumbnail[62] = new Image();
  thumbnail[62].src = "img/myndir/thumbnail/63.jpg";
  thumbnail[63] = new Image();
  thumbnail[63].src = "img/myndir/thumbnail/64.jpg";
  thumbnail[64] = new Image();
  thumbnail[64].src = "img/myndir/thumbnail/65.jpg";
  thumbnail[65] = new Image();
  thumbnail[65].src = "img/myndir/thumbnail/66.jpg";
  thumbnail[66] = new Image();
  thumbnail[66].src = "img/myndir/thumbnail/67.jpg";
  thumbnail[67] = new Image();
  thumbnail[67].src = "img/myndir/thumbnail/68.jpg";
  thumbnail[68] = new Image();
  thumbnail[68].src = "img/myndir/thumbnail/69.jpg";
  thumbnail[69] = new Image();
  thumbnail[69].src = "img/myndir/thumbnail/70.jpg";
  thumbnail[70] = new Image();
  thumbnail[70].src = "img/myndir/thumbnail/71.jpg";
  thumbnail[71] = new Image();
  thumbnail[71].src = "img/myndir/thumbnail/72.jpg";
  thumbnail[72] = new Image();
  thumbnail[72].src = "img/myndir/thumbnail/73.jpg";
  thumbnail[73] = new Image();
  thumbnail[73].src = "img/myndir/thumbnail/74.jpg";
  thumbnail[74] = new Image();
  thumbnail[74].src = "img/myndir/thumbnail/75.jpg";
  thumbnail[75] = new Image();
  thumbnail[75].src = "img/myndir/thumbnail/76.jpg";
  thumbnail[76] = new Image();
  thumbnail[76].src = "img/myndir/thumbnail/77.jpg";
  thumbnail[77] = new Image();
  thumbnail[77].src = "img/myndir/thumbnail/78.jpg";
  thumbnail[78] = new Image();
  thumbnail[78].src = "img/myndir/thumbnail/79.jpg";
  thumbnail[79] = new Image();
  thumbnail[79].src = "img/myndir/thumbnail/80.jpg";
  thumbnail[80] = new Image();
  thumbnail[80].src = "img/myndir/thumbnail/81.jpg";
  thumbnail[81] = new Image();
  thumbnail[81].src = "img/myndir/thumbnail/82.jpg";
  thumbnail[82] = new Image();
  thumbnail[82].src = "img/myndir/thumbnail/83.jpg";
  thumbnail[83] = new Image();
  thumbnail[83].src = "img/myndir/thumbnail/84.jpg";
  thumbnail[84] = new Image();
  thumbnail[84].src = "img/myndir/thumbnail/85.jpg";
  thumbnail[85] = new Image();
  thumbnail[85].src = "img/myndir/thumbnail/86.jpg";
  thumbnail[86] = new Image();
  thumbnail[86].src = "img/myndir/thumbnail/87.jpg";
  thumbnail[87] = new Image();
  thumbnail[87].src = "img/myndir/thumbnail/88.jpg";
  thumbnail[88] = new Image();
  thumbnail[88].src = "img/myndir/thumbnail/89.jpg";
  thumbnail[89] = new Image();
  thumbnail[89].src = "img/myndir/thumbnail/90.jpg";
  thumbnail[90] = new Image();
  thumbnail[90].src = "img/myndir/thumbnail/91.jpg";
  thumbnail[91] = new Image();
  thumbnail[91].src = "img/myndir/thumbnail/92.jpg";
  thumbnail[92] = new Image();
  thumbnail[92].src = "img/myndir/thumbnail/93.jpg";
  thumbnail[93] = new Image();
  thumbnail[93].src = "img/myndir/thumbnail/94.jpg";
  thumbnail[94] = new Image();
  thumbnail[94].src = "img/myndir/thumbnail/95.jpg";
  thumbnail[95] = new Image();
  thumbnail[95].src = "img/myndir/thumbnail/96.jpg";
  thumbnail[96] = new Image();
  thumbnail[96].src = "img/myndir/thumbnail/97.jpg";
  thumbnail[97] = new Image();
  thumbnail[97].src = "img/myndir/thumbnail/98.jpg";
  thumbnail[98] = new Image();
  thumbnail[98].src = "img/myndir/thumbnail/99.jpg";
  thumbnail[99] = new Image();
  thumbnail[99].src = "img/myndir/thumbnail/100.jpg";
  thumbnail[100] = new Image();
  thumbnail[100].src = "img/myndir/thumbnail/101.jpg";
  thumbnail[101] = new Image();
  thumbnail[101].src = "img/myndir/thumbnail/102.jpg";
  thumbnail[102] = new Image();
  thumbnail[102].src = "img/myndir/thumbnail/103.jpg";
  thumbnail[103] = new Image();
  thumbnail[103].src = "img/myndir/thumbnail/104.jpg";
  thumbnail[104] = new Image();
  thumbnail[104].src = "img/myndir/thumbnail/105.jpg";
  thumbnail[105] = new Image();
  thumbnail[105].src = "img/myndir/thumbnail/106.jpg";
  thumbnail[106] = new Image();
  thumbnail[106].src = "img/myndir/thumbnail/107.jpg";
  thumbnail[107] = new Image();
  thumbnail[107].src = "img/myndir/thumbnail/108.jpg";
  thumbnail[108] = new Image();
  thumbnail[108].src = "img/myndir/thumbnail/109.jpg";
  thumbnail[109] = new Image();
  thumbnail[109].src = "img/myndir/thumbnail/110.jpg";
  thumbnail[110] = new Image();
  thumbnail[110].src = "img/myndir/thumbnail/111.jpg";
  thumbnail[111] = new Image();
  thumbnail[111].src = "img/myndir/thumbnail/112.jpg";
  thumbnail[112] = new Image();
  thumbnail[112].src = "img/myndir/thumbnail/113.jpg";
  thumbnail[113] = new Image();
  thumbnail[113].src = "img/myndir/thumbnail/114.jpg";
  thumbnail[114] = new Image();
  thumbnail[114].src = "img/myndir/thumbnail/115.jpg";
  thumbnail[115] = new Image();
  thumbnail[115].src = "img/myndir/thumbnail/116.jpg";
  thumbnail[116] = new Image();
  thumbnail[116].src = "img/myndir/thumbnail/117.jpg";
  thumbnail[117] = new Image();
  thumbnail[117].src = "img/myndir/thumbnail/118.jpg";
  thumbnail[118] = new Image();
  thumbnail[118].src = "img/myndir/thumbnail/119.jpg";
  thumbnail[119] = new Image();
  thumbnail[119].src = "img/myndir/thumbnail/120.jpg";
  thumbnail[120] = new Image();
  thumbnail[120].src = "img/myndir/thumbnail/121.jpg";
  thumbnail[121] = new Image();
  thumbnail[121].src = "img/myndir/thumbnail/122.jpg";
  thumbnail[122] = new Image();
  thumbnail[122].src = "img/myndir/thumbnail/123.jpg";
  thumbnail[123] = new Image();
  thumbnail[123].src = "img/myndir/thumbnail/124.jpg";
  thumbnail[124] = new Image();
  thumbnail[124].src = "img/myndir/thumbnail/125.jpg";
  thumbnail[125] = new Image();
  thumbnail[125].src = "img/myndir/thumbnail/126.jpg";
  thumbnail[126] = new Image();
  thumbnail[126].src = "img/myndir/thumbnail/127.jpg";
  thumbnail[127] = new Image();
  thumbnail[127].src = "img/myndir/thumbnail/128.jpg";
  thumbnail[128] = new Image();
  thumbnail[128].src = "img/myndir/thumbnail/129.jpg";
  thumbnail[129] = new Image();
  thumbnail[129].src = "img/myndir/thumbnail/130.jpg";
  thumbnail[130] = new Image();
  thumbnail[130].src = "img/myndir/thumbnail/131.jpg";
  thumbnail[131] = new Image();
  thumbnail[131].src = "img/myndir/thumbnail/132.jpg";
  
  $(litlarm[0]).css("opacity", "0.0");
  
  var myndateljari = 0;
  
  $("#or2").click(function() {
    $(litlarm[myndateljari]).css("opacity", "0.6");
    myndateljari++;
    if(myndateljari == myndasyning.length) {
	myndateljari=0;
	}
	$("#myndarammi").css("background-image", "url(" + myndasyning[myndateljari].src + ")");
	$("#myndatexti").text(myndasyningtexti[myndateljari]);
	$(litlarm[myndateljari]).css("opacity", "0.0");
  });
  
  $("#or1").click(function() {
    $(litlarm[myndateljari]).css("opacity", "0.6");
    myndateljari--;
    if(myndateljari < 0) {
	myndateljari=(myndasyning.length-1);
	}
    $("#myndarammi").css("background-image", "url(" + myndasyning[myndateljari].src + ")");
	$("#myndatexti").text(myndasyningtexti[myndateljari]);
	$(litlarm[myndateljari]).css("opacity", "0.0");
  });
  
  for(i=0; i<litlarmyndir.length; i++) {
  $(litlarmyndir[i]).css("background-image", "url(" + thumbnail[i].src + ")");
  }
  
  $("body").keydown(function(e) {
      if(e.which == 37) { 
      $(litlarm[myndateljari]).css("opacity", "0.6");
      myndateljari--;
      if(myndateljari < 0) {
	  myndateljari=(myndasyning.length-1);
	  }
      $("#myndarammi").css("background-image", "url(" + myndasyning[myndateljari].src + ")");
	  $("#myndatexti").text(myndasyningtexti[myndateljari]);
      $(litlarm[myndateljari]).css("opacity", "0.0");   
      }
      else if(e.which == 39) { 
      $(litlarm[myndateljari]).css("opacity", "0.6");
      myndateljari++;
      if(myndateljari == myndasyning.length) {
	  myndateljari=0;
	  }
	  $("#myndarammi").css("background-image", "url(" + myndasyning[myndateljari].src + ")");
	  $("#myndatexti").text(myndasyningtexti[myndateljari]);
	  $(litlarm[myndateljari]).css("opacity", "0.0");
     }
  });
  
  $(function(){
  litlarm.forEach(function(mafs, index){
  $(litlarm[index]).click(function() {
  $(litlarm[myndateljari]).css("opacity", "0.6");
  myndateljari = index;
  $(litlarm[index]).css("opacity", "0.0");
  $("#myndarammi").css("background-image", "url(" + myndasyning[myndateljari].src + ")");
  $("#myndatexti").text(myndasyningtexti[myndateljari]);
 })})});
});